// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using settings4net.Core.APIClient.Models;

namespace settings4net.Core.APIClient.Models
{
    public static partial class SettingCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Setting> DeserializeJson(JToken inputObject)
        {
            IList<Setting> deserializedObject = new List<Setting>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Setting setting = new Setting();
                setting.DeserializeJson(iListValue);
                deserializedObject.Add(setting);
            }
            return deserializedObject;
        }
    }
}
